// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/exchange.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Period        int32                  `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticRequest) Reset() {
	*x = AnalyticRequest{}
	mi := &file_proto_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticRequest) ProtoMessage() {}

func (x *AnalyticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticRequest.ProtoReflect.Descriptor instead.
func (*AnalyticRequest) Descriptor() ([]byte, []int) {
	return file_proto_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyticRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AnalyticRequest) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

type AnalyticResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,2,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	RsiValue      float64                `protobuf:"fixed64,3,opt,name=rsi_value,json=rsiValue,proto3" json:"rsi_value,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyticResponse) Reset() {
	*x = AnalyticResponse{}
	mi := &file_proto_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticResponse) ProtoMessage() {}

func (x *AnalyticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticResponse.ProtoReflect.Descriptor instead.
func (*AnalyticResponse) Descriptor() ([]byte, []int) {
	return file_proto_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyticResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AnalyticResponse) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *AnalyticResponse) GetRsiValue() float64 {
	if x != nil {
		return x.RsiValue
	}
	return 0
}

func (x *AnalyticResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_exchange_proto protoreflect.FileDescriptor

const file_proto_exchange_proto_rawDesc = "" +
	"\n" +
	"\x14proto/exchange.proto\x12\x02pb\"A\n" +
	"\x0fAnalyticRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x05R\x06period\"\x84\x01\n" +
	"\x10AnalyticResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12#\n" +
	"\rcurrent_price\x18\x02 \x01(\x01R\fcurrentPrice\x12\x1b\n" +
	"\trsi_value\x18\x03 \x01(\x01R\brsiValue\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2G\n" +
	"\x10AnalyticsService\x123\n" +
	"\x06GetRSI\x12\x13.pb.AnalyticRequest\x1a\x14.pb.AnalyticResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_exchange_proto_rawDescOnce sync.Once
	file_proto_exchange_proto_rawDescData []byte
)

func file_proto_exchange_proto_rawDescGZIP() []byte {
	file_proto_exchange_proto_rawDescOnce.Do(func() {
		file_proto_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exchange_proto_rawDesc), len(file_proto_exchange_proto_rawDesc)))
	})
	return file_proto_exchange_proto_rawDescData
}

var file_proto_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_exchange_proto_goTypes = []any{
	(*AnalyticRequest)(nil),  // 0: pb.AnalyticRequest
	(*AnalyticResponse)(nil), // 1: pb.AnalyticResponse
}
var file_proto_exchange_proto_depIdxs = []int32{
	0, // 0: pb.AnalyticsService.GetRSI:input_type -> pb.AnalyticRequest
	1, // 1: pb.AnalyticsService.GetRSI:output_type -> pb.AnalyticResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_exchange_proto_init() }
func file_proto_exchange_proto_init() {
	if File_proto_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exchange_proto_rawDesc), len(file_proto_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exchange_proto_goTypes,
		DependencyIndexes: file_proto_exchange_proto_depIdxs,
		MessageInfos:      file_proto_exchange_proto_msgTypes,
	}.Build()
	File_proto_exchange_proto = out.File
	file_proto_exchange_proto_goTypes = nil
	file_proto_exchange_proto_depIdxs = nil
}
